function A = A_fun(in1)
%A_FUN
%    A = A_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    13-Jul-2023 16:57:25

phi = in1(1,:);
psi = in1(3,:);
tet = in1(2,:);
t2 = cos(phi);
t3 = cos(psi);
t4 = cos(tet);
t5 = sin(phi);
t6 = sin(psi);
t7 = sin(tet);
A = reshape([t3.*t4,t5.*t7+t2.*t4.*t6,-t2.*t7+t4.*t5.*t6,-t6,t2.*t3,t3.*t5,t3.*t7,-t4.*t5+t2.*t6.*t7,t2.*t4+t5.*t6.*t7],[3,3]);
