function A = Af(e0,e1,e2,e3)
%AF
%    A = AF(E0,E1,E2,E3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    11-Sep-2023 07:35:46

t2 = e0.^2;
t3 = e0.*e1.*2.0;
t4 = e0.*e2.*2.0;
t5 = e0.*e3.*2.0;
t6 = e1.*e2.*2.0;
t7 = e1.*e3.*2.0;
t8 = e2.*e3.*2.0;
t9 = t2.*2.0;
A = reshape([t9+e1.^2.*2.0-1.0,t5+t6,-t4+t7,-t5+t6,t9+e2.^2.*2.0-1.0,t3+t8,t4+t7,-t3+t8,t9+e3.^2.*2.0-1.0],[3,3]);
