function dA = dAf(de0,de1,de2,de3,e0,e1,e2,e3)
%DAF
%    DA = DAF(DE0,DE1,DE2,DE3,E0,E1,E2,E3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    11-Sep-2023 07:35:46

t2 = de0.*e1.*2.0;
t3 = de1.*e0.*2.0;
t4 = de0.*e0.*4.0;
t5 = de0.*e2.*2.0;
t6 = de2.*e0.*2.0;
t7 = de0.*e3.*2.0;
t8 = de1.*e2.*2.0;
t9 = de2.*e1.*2.0;
t10 = de3.*e0.*2.0;
t11 = de1.*e3.*2.0;
t12 = de3.*e1.*2.0;
t13 = de2.*e3.*2.0;
t14 = de3.*e2.*2.0;
dA = reshape([t4+de1.*e1.*4.0,t7+t8+t9+t10,-t5-t6+t11+t12,-t7+t8+t9-t10,t4+de2.*e2.*4.0,t2+t3+t13+t14,t5+t6+t11+t12,-t2-t3+t13+t14,t4+de3.*e3.*4.0],[3,3]);
