function F_n = F_n_bend(a,in2,in3,in4,in5,a0,k_b)
%F_n_bend
%    F_n = F_n_bend(A,IN2,IN3,IN4,IN5,A0,K_B)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jan-2024 18:18:26

pos_c1 = in4(1,:);
pos_c2 = in4(2,:);
pos_c3 = in4(3,:);
pos_n1 = in5(1,:);
pos_n2 = in5(2,:);
pos_n3 = in5(3,:);
pos_p1 = in3(1,:);
pos_p2 = in3(2,:);
pos_p3 = in3(3,:);
t1 = in2(1,:);
t2 = in2(2,:);
t3 = in2(3,:);
t5 = -a0;
t6 = -pos_p1;
t7 = -pos_p2;
t8 = -pos_p3;
t9 = a+t5;
t10 = pos_c1+t6;
t11 = pos_c2+t7;
t12 = pos_c3+t8;
t13 = t10.^2;
t14 = t11.^2;
t15 = t12.^2;
t16 = t13+t14+t15;
t17 = 1.0./t16;
F_n = [k_b.*t9.*t17.*(pos_c2.*t3-pos_c3.*t2-pos_n2.*t3+pos_n3.*t2);-k_b.*t9.*t17.*(pos_c1.*t3-pos_c3.*t1-pos_n1.*t3+pos_n3.*t1);k_b.*t9.*t17.*(pos_c1.*t2-pos_c2.*t1-pos_n1.*t2+pos_n2.*t1)];
end
