function Force_el = Force_Spring(in1,in2,cp,l0)
%Force_Spring
%    Force_el = Force_Spring(IN1,IN2,CP,L0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jan-2024 18:18:24

e_c1 = in1(1,:);
e_c2 = in1(2,:);
e_c3 = in1(3,:);
e_s1 = in2(1,:);
e_s2 = in2(2,:);
e_s3 = in2(3,:);
t2 = -e_s1;
t3 = -e_s2;
t4 = -e_s3;
t5 = e_c1+t2;
t6 = e_c2+t3;
t7 = e_c3+t4;
t8 = abs(t5);
t9 = abs(t6);
t10 = abs(t7);
t11 = t8.^2;
t12 = t9.^2;
t13 = t10.^2;
t14 = t11+t12+t13;
t15 = sqrt(t14);
t16 = 1.0./t15;
t17 = -t15;
t18 = l0+t17;
Force_el = [-cp.*t5.*t16.*t18;-cp.*t6.*t16.*t18;-cp.*t7.*t16.*t18];
end
